/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LoadSvgResult {
  success: boolean
  result: string
}
export declare function loadSvgString(svgData: string): LoadSvgResult
export declare function loadSvgFile(svgPath: string): LoadSvgResult
