/* eslint-disable */
/* tslint:disable */
/* auto-generated by NAPI-RS */

export interface Point {
  x: number
  y: number
}

export interface Polygon {
  outer: Array<Point>
  inner?: Array<Array<Point>> // Optional: list of inner hole paths
}

export function noFitPolygon(
  polygonA: Polygon,      // Stationary polygon, can have holes
  polygonB: Polygon,      // Orbiting polygon, its 'inner' holes are effectively ignored by current babushka MultiPolygon NFP logic
  includeOuterNfp: boolean, // If true, compute NFP of polygonA's outer boundary against polygonB's outer boundary
  includeHolesNfp: boolean  // If true, compute NFPs of polygonA's inner holes against polygonB's outer boundary
): Array<Array<Point>>      // Returns an array of NFP paths. An empty array means no NFP was generated.
